/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    copy: typeof import('./src/components/NumberFilterField copy.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DateFilterField: typeof import('./src/components/DateFilterField.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Divider: typeof import('primevue/divider')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FilterBlock: typeof import('./src/components/FilterBlock.vue')['default']
    FilterField: typeof import('./src/components/FilterField.vue')['default']
    FilterForm: typeof import('./src/components/FilterForm.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    NumberFilterField: typeof import('./src/components/NumberFilterField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    StringFilterField: typeof import('./src/components/StringFilterField.vue')['default']
    StringFormField: typeof import('./src/components/StringFormField.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}

// For TSX support
declare global {
  const Button: typeof import('primevue/button')['default']
  const Card: typeof import('primevue/card')['default']
  const Column: typeof import('primevue/column')['default']
  const copy: typeof import('./src/components/NumberFilterField copy.vue')['default']
  const DataTable: typeof import('primevue/datatable')['default']
  const DateFilterField: typeof import('./src/components/DateFilterField.vue')['default']
  const DatePicker: typeof import('primevue/datepicker')['default']
  const Divider: typeof import('primevue/divider')['default']
  const Fieldset: typeof import('primevue/fieldset')['default']
  const FilterBlock: typeof import('./src/components/FilterBlock.vue')['default']
  const FilterField: typeof import('./src/components/FilterField.vue')['default']
  const FilterForm: typeof import('./src/components/FilterForm.vue')['default']
  const FloatLabel: typeof import('primevue/floatlabel')['default']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
  const IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
  const IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
  const IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
  const IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
  const InputNumber: typeof import('primevue/inputnumber')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const NumberFilterField: typeof import('./src/components/NumberFilterField.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Select: typeof import('primevue/select')['default']
  const StringFilterField: typeof import('./src/components/StringFilterField.vue')['default']
  const StringFormField: typeof import('./src/components/StringFormField.vue')['default']
  const TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
  const WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
}